# This is Numpy Lecture

In [50]:
# Cell 1 – Setup & Basic Info

import numpy as np

print("NumPy version:", np.__version__)

# NumPy = Numerical Python
# - Core idea: multidimensional arrays (ndarray)
# - Fast, vectorized operations (avoid Python loops as much as possible)


NumPy version: 2.1.3


In [54]:
# Cell 2 – Creating Arrays (1D, 2D, 3D) and Inspecting Shape & Dimensions

# 1D array (vector)
a1 = np.array([1, 2, 3, 4, 5])
print("a1:", a1)
print("a1.ndim (dimensions):", a1.ndim)
print("a1.shape (rows, cols,...):", a1.shape)

# 2D array (matrix)
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print("\na2:\n", a2)
print("a2.ndim:", a2.ndim)
print("a2.shape:", a2.shape)

# 3D array (e.g., batch, rows, cols)
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\na3:\n", a3)
print("a3.ndim:", a3.ndim)
print("a3.shape:", a3.shape)


a1: [1 2 3 4 5]
a1.ndim (dimensions): 1
a1.shape (rows, cols,...): (5,)

a2:
 [[1 2 3]
 [4 5 6]]
a2.ndim: 2
a2.shape: (2, 3)

a3:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
a3.ndim: 3
a3.shape: (2, 2, 2)


In [55]:
# Cell 3 – Special Arrays (zeros, ones, arrange, linspace)

zeros = np.zeros((2, 3))   # 2x3 matrix of 0
ones = np.ones((3, 2))     # 3x2 matrix of 1
eye = np.eye(3)            # 3x3 identity matrix

print("zeros:\n", zeros)
print("\nones:\n", ones)
print("\neye (identity):\n", eye)

# arrange: like Python range but returns array
arr_range = np.arange(0, 10, 2)  # 0..8 step 2
print("\narr_range:", arr_range)

# linspace: n equally spaced points between start and end (inclusive)
arr_lin = np.linspace(0, 1, 5)
print("arr_lin:", arr_lin)


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

eye (identity):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arr_range: [0 2 4 6 8]
arr_lin: [0.   0.25 0.5  0.75 1.  ]


In [56]:
# Cell 4 – Data Types (dtype)


arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])
arr_mixed = np.array([1, 2.5, 3])  # upcasted to float

print("arr_int:", arr_int, "| dtype:", arr_int.dtype)
print("arr_float:", arr_float, "| dtype:", arr_float.dtype)
print("arr_mixed:", arr_mixed, "| dtype:", arr_mixed.dtype)

# Force a specific dtype
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print("\narr_int32:", arr_int32, "| dtype:", arr_int32.dtype)

# Change dtype (copy)
arr_float64 = arr_int32.astype(np.float64)
print("arr_float64:", arr_float64, "| dtype:", arr_float64.dtype)


arr_int: [1 2 3] | dtype: int64
arr_float: [1. 2. 3.] | dtype: float64
arr_mixed: [1.  2.5 3. ] | dtype: float64

arr_int32: [1 2 3] | dtype: int32
arr_float64: [1. 2. 3.] | dtype: float64


In [57]:
# Cell 5 – Indexing & Slicing (1D and 2D)

b = np.array([10, 20, 30, 40, 50])
print("b:", b)
print("b[0]:", b[0])      # first element
print("b[-1]:", b[-1])    # last element

print("\nSlice examples:")
print("b[1:4]:", b[1:4])    # index 1,2,3
print("b[:3]:", b[:3])      # start to 2
print("b[::2]:", b[::2])    # step of 2

# 2D indexing
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("\nc:\n", c)
print("Element at row 0, col 1:", c[0, 1])
print("First row:", c[0, :])
print("Second column:", c[:, 1])
print("Sub-matrix (rows 0-1, cols 1-2):\n", c[0:2, 1:3])


b: [10 20 30 40 50]
b[0]: 10
b[-1]: 50

Slice examples:
b[1:4]: [20 30 40]
b[:3]: [10 20 30]
b[::2]: [10 30 50]

c:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, col 1: 2
First row: [1 2 3]
Second column: [2 5 8]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]


In [58]:
# Cell 6 – Boolean Indexing & Filtering

d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Condition creates a boolean mask
mask = d > 4
print("d:", d)
print("mask (d > 4):", mask)

# Use mask to filter
print("d[d > 4]:", d[d > 4])

# Combine conditions
print("Even numbers > 4:", d[(d > 4) & (d % 2 == 0)])


d: [1 2 3 4 5 6 7 8 9]
mask (d > 4): [False False False False  True  True  True  True  True]
d[d > 4]: [5 6 7 8 9]
Even numbers > 4: [6 8]


In [60]:
# Cell 7 – Basic Operations & Broadcasting

x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("x:", x)
print("y:", y)

# Element-wise operations
print("x + y:", x + y)
print("x * y:", x * y)
print("x ** 2:", x ** 2)

# Broadcasting: scalar with array
print("\nx + 5:", x + 5)
print("x * 10:", x * 10)

# Broadcasting 1D with 2D
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("\nm:\n", m)
print("m + x:\n", m + x)   # x is broadcast across rows


x: [1 2 3]
y: [10 20 30]
x + y: [11 22 33]
x * y: [10 40 90]
x ** 2: [1 4 9]

x + 5: [6 7 8]
x * 10: [10 20 30]

m:
 [[1 2 3]
 [4 5 6]]
m + x:
 [[2 4 6]
 [5 7 9]]


In [59]:
# Cell 9 – Reshaping, Flattening, Transpose

e = np.arange(12)   # 0..11
print("e:", e)
print("e.shape:", e.shape)

# Reshape into 3x4
e_3x4 = e.reshape(3, 4)
print("\ne_3x4:\n", e_3x4)

# Flatten back to 1D
print("\nFlattened (ravel):", e_3x4.ravel())

# Transpose (rows ↔ columns)
print("\nTranspose of e_3x4:\n", e_3x4.T)
print("Shapes: original", e_3x4.shape, "| transposed", e_3x4.T.shape)


e: [ 0  1  2  3  4  5  6  7  8  9 10 11]
e.shape: (12,)

e_3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened (ravel): [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose of e_3x4:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Shapes: original (3, 4) | transposed (4, 3)


In [61]:
# Cell 10 – Stacking & Splitting Arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a)
print("b:", b)

# Stacking vertically & horizontally (2D)
v_stack = np.vstack([a, b])   # 2 rows
h_stack = np.hstack([a, b])   # 1 row, 6 columns

print("\nVertical stack:\n", v_stack)
print("\nHorizontal stack:\n", h_stack)

# Split an array into parts
split_arr = np.array([10, 20, 30, 40, 50, 60])
print("\nsplit_arr:", split_arr)

# Split into 3 equal parts
parts = np.split(split_arr, 3)
print("Split into 3 parts:", parts)


a: [1 2 3]
b: [4 5 6]

Vertical stack:
 [[1 2 3]
 [4 5 6]]

Horizontal stack:
 [1 2 3 4 5 6]

split_arr: [10 20 30 40 50 60]
Split into 3 parts: [array([10, 20]), array([30, 40]), array([50, 60])]


In [62]:
# Cell 11 – Random Numbers

# NOTE: new NumPy recommends using np.random.default_rng()
rng = np.random.default_rng(seed=42)  # seed for reproducibility

# Random floats in [0, 1)
rand_floats = rng.random(5)
print("Random floats:", rand_floats)

# Random integers between 0 and 9
rand_ints = rng.integers(low=0, high=10, size=(2, 3))
print("\nRandom integers 2x3:\n", rand_ints)

# Normal distribution (mean=0, std=1)
rand_normal = rng.normal(loc=0, scale=1, size=5)
print("\nRandom normal:", rand_normal)


Random floats: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]

Random integers 2x3:
 [[5 9 7]
 [7 7 7]]

Random normal: [-0.01680116 -0.85304393  0.87939797  0.77779194  0.0660307 ]


In [63]:
# Cell 12 – Vectorization vs Python Loops

# Example: square each element of a large array

# Python loop
def python_square(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

# NumPy vectorized
def numpy_square(values):
    return values * values

large_arr = np.arange(1_000_000)

# Timing in Jupyter: use magic %timeit
print("Use in notebook:")
print("%timeit python_square(large_arr)")
print("%timeit numpy_square(large_arr)")

# Run the above %timeit directly in Jupyter for real timings.


Use in notebook:
%timeit python_square(large_arr)
%timeit numpy_square(large_arr)


In [64]:
# Cell 13 – Handling NaN and Infinity

arr_nan = np.array([1, 2, np.nan, 4, np.inf, -np.inf])
print("arr_nan:", arr_nan)

# isnan, isfinite, isinf
print("isnan:", np.isnan(arr_nan))
print("isfinite:", np.isfinite(arr_nan))
print("isinf:", np.isinf(arr_nan))

# Useful: ignore NaN in aggregations
arr_with_nan = np.array([1, 2, np.nan, 4])
print("\narr_with_nan:", arr_with_nan)
print("np.nanmean:", np.nanmean(arr_with_nan))  # ignores NaN
print("np.nansum:", np.nansum(arr_with_nan))    # ignores NaN


arr_nan: [  1.   2.  nan   4.  inf -inf]
isnan: [False False  True False False False]
isfinite: [ True  True False  True False False]
isinf: [False False False False  True  True]

arr_with_nan: [ 1.  2. nan  4.]
np.nanmean: 2.3333333333333335
np.nansum: 7.0


In [65]:
# Cell 14 – Basic Linear Algebra

# Matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("A:\n", A)
print("\nB:\n", B)

# Matrix multiplication (dot product)
C = A @ B        # same as np.dot(A, B)
print("\nA @ B:\n", C)

# Determinant, inverse, eigenvalues
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

eig_vals, eig_vecs = np.linalg.eig(A)
print("\nEigenvalues of A:", eig_vals)
print("Eigenvectors of A:\n", eig_vecs)


A:
 [[1 2]
 [3 4]]

B:
 [[5 6]
 [7 8]]

A @ B:
 [[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [66]:
# Cell 15 – Practical Mini-Example: Simple Statistics

# Imagine these are student marks in 5 subjects for 4 students
marks = np.array([
    [85, 90, 78, 92, 88],
    [72, 75, 70, 80, 78],
    [90, 88, 95, 93, 91],
    [60, 65, 58, 62, 64]
])

print("marks:\n", marks)

# Average marks per student (across columns)
avg_per_student = marks.mean(axis=1)
print("\nAverage per student:", avg_per_student)

# Average marks per subject (down the rows)
avg_per_subject = marks.mean(axis=0)
print("Average per subject:", avg_per_subject)

# Highest mark for each subject
max_per_subject = marks.max(axis=0)
print("Max per subject:", max_per_subject)

# Which student has the highest overall average?
top_student_index = np.argmax(avg_per_student)
print("\nTop student index (0-based):", top_student_index)
print("Top student average:", avg_per_student[top_student_index])


marks:
 [[85 90 78 92 88]
 [72 75 70 80 78]
 [90 88 95 93 91]
 [60 65 58 62 64]]

Average per student: [86.6 75.  91.4 61.8]
Average per subject: [76.75 79.5  75.25 81.75 80.25]
Max per subject: [90 90 95 93 91]

Top student index (0-based): 2
Top student average: 91.4
